server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: pk2258

#  jackson:
#    serialization:
#      fail-on-empty-beans: false

  datasource:
    url: jdbc:mysql://localhost/rankingDB?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: pk2258
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect